### ISSUE TITLE
getInput() looks not worked

### ISSUE THREAD

**Issue by say8425** [say8425/aws-secrets-manager-actions#6]
```shell script
Run say8425/aws-secrets-manager-actions@v0.9.1
 with:
   AWS_ACCESS_KEY_ID: ***
   AWS_SECRET_ACCESS_KEY: ***
   AWS_DEFAULT_REGION: ap-northeast-2
   SECRET_NAME: pongdang-env-test
/home/runner/work/_actions/say8425/aws-secrets-manager-actions/v0.9.1/dist/index.js:208
const secretName = _actions_core__WEBPACK_IMPORTED_MODULE_0___default().getInput('SECRET_NAME')

TypeError: Cannot read property 'getInput' of undefined
  at Module.104 (/home/runner/work/_actions/say8425/aws-secrets-manager-actions/v0.9.1/dist/index.js:208:72)
  at __webpack_require__ (/home/runner/work/_actions/say8425/aws-secrets-manager-actions/v0.9.1/dist/index.js:22:30)
  at startup (/home/runner/work/_actions/say8425/aws-secrets-manager-actions/v0.9.1/dist/index.js:37:19)
  at /home/runner/work/_actions/say8425/aws-secrets-manager-actions/v0.9.1/dist/index.js:43:18
  at Object.<anonymous> (/home/runner/work/_actions/say8425/aws-secrets-manager-actions/v0.9.1/dist/index.js:46:10)
  at Module._compile (internal/modules/cjs/loader.js:774:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
  at Module.load (internal/modules/cjs/loader.js:641:32)
  at Function.Module._load (internal/modules/cjs/loader.js:556:12)
  at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
##[error]Node run failed with exit code 1
```
looks github core module not imported well.
https://github.com/say8425/PongDang-API/runs/299328097

**Comment by say8425** [comment]
FIxed it https://github.com/say8425/aws-secrets-manager-actions/commit/6067419f47e636856a9ea8002f2d7b2172396046#diff-168726dbe96b3ce427e7fedce31bb0bc
